# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DtrackUpload < Formula
  desc "Minimal CLI to upload CycloneDX SBOMs to Dependency Track"
  homepage "https://github.com/dirsigler/dtrack-upload"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirsigler/dtrack-upload/releases/download/v0.2.0/dtrack-upload_0.2.0_darwin_amd64.tar.gz"
      sha256 "991d50c94138fa3ed3c67b9baddee7f61378592f82aa41d3e61b15fd7f1875aa"

      define_method(:install) do
        bin.install "dtrack-upload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirsigler/dtrack-upload/releases/download/v0.2.0/dtrack-upload_0.2.0_darwin_arm64.tar.gz"
      sha256 "9d97462cb1994b7517410d799774ef82d585682727cb3f10793893b81ca04c57"

      define_method(:install) do
        bin.install "dtrack-upload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirsigler/dtrack-upload/releases/download/v0.2.0/dtrack-upload_0.2.0_linux_amd64.tar.gz"
      sha256 "91b7e5c1472c48e44736d9b8ac2ce0e69879279b346f4d4853ac5f7d89c5d58c"
      define_method(:install) do
        bin.install "dtrack-upload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirsigler/dtrack-upload/releases/download/v0.2.0/dtrack-upload_0.2.0_linux_arm64.tar.gz"
      sha256 "d60c136328bde3d0f47b53c659e7e6894507598a0653258399fa8bb0ae133800"
      define_method(:install) do
        bin.install "dtrack-upload"
      end
    end
  end

  test do
    system "#{bin}/dtrack-upload", "--version"
  end
end
