# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DtrackUpload < Formula
  desc "Minimal CLI to upload CycloneDX SBOMs to Dependency Track"
  homepage "https://github.com/dirsigler/dtrack-upload"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirsigler/dtrack-upload/releases/download/v0.4.0/dtrack-upload_0.4.0_darwin_amd64.tar.gz"
      sha256 "9dd0b1ed3cfaf07ad89d5df2b4ee43254fffcbf8b2684298700e485328530797"

      define_method(:install) do
        bin.install "dtrack-upload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirsigler/dtrack-upload/releases/download/v0.4.0/dtrack-upload_0.4.0_darwin_arm64.tar.gz"
      sha256 "f738b7005395d387b8d98e0bd8f940b2f4f919302831cef37c8681546a7de315"

      define_method(:install) do
        bin.install "dtrack-upload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirsigler/dtrack-upload/releases/download/v0.4.0/dtrack-upload_0.4.0_linux_amd64.tar.gz"
      sha256 "b71be8057ee379a189e8f8de085f6dd35dd87411ae71b7a50665d1b2cab415e1"
      define_method(:install) do
        bin.install "dtrack-upload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirsigler/dtrack-upload/releases/download/v0.4.0/dtrack-upload_0.4.0_linux_arm64.tar.gz"
      sha256 "e115da2af39b84267df68ffdc55b8ce0d8ec887abac33e9da62676215dc86e04"
      define_method(:install) do
        bin.install "dtrack-upload"
      end
    end
  end

  test do
    system "#{bin}/dtrack-upload", "--version"
  end
end
